config/routes.rb
Rails.application.routes.draw do
  resources :quizzes, except: [:new, :edit, :destroy, :show]
  get    '/quizzes/new',     to: 'quizzes#new',     as: 'new_quiz'
  post   '/quizzes/create',  to: 'quizzes#create',  as: 'create_quiz'
  get    '/quizzes/show',    to: 'quizzes#show',    as: 'show_quiz'
  get    '/quizzes/edit',    to: 'quizzes#edit',    as: 'edit_quiz'
  patch  '/quizzes/update',  to: 'quizzes#update',  as: 'update_quiz'
  delete '/quizzes/destroy', to: 'quizzes#destroy', as: 'destroy_quiz'
  
  get '/about', to: 'about#new'

  root to: 'home#new'

  devise_for :users, controllers:{
    session: 'users/sessions',
    registrations: 'users/registrations'
  }

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :admin_only, except: [:create, :update]

  def new
    @quiz = Quiz.new
  end

  def create
    quiz = Quiz.new
    quiz.name       = params[:quiz][:name]
    quiz.difficulty = params[:quiz][:difficulty]
    if quiz.save
      flash[:notice] = 'Quiz successfully Initiated'
      redirect_to show_quiz_path(id: quiz.id)
    else
      flash[:alert]  = 'Something went wrong: Generating quiz'
      render :new
    end
  end

  def edit
    @quiz = Quiz.find(params[:id].to_i)
  end

  def update
    quiz = Quiz.find(params[:quiz][:id].to_i)
    quiz.name       = params[:quiz][:name]
    quiz.difficulty = params[:quiz][:difficulty]
    if quiz.save
      flash[:notice] = 'Quiz.successfulyl updated'
      redirect_to show_quiz_path(id: quiz.id)
    else
      flash[:alert]  = 'Something went wrong: updating quiz'
      render :edit
    end
  end
  
  def show
    @quiz = Quiz.find(params[:id].to_i)
  end

  def destroy
    @quiz = Quiz.find(params[:id].to_i)
    debugger
  end

  private
  
  def admin_only
    redirect_to root_path, alert:'Access denied, non-ADMIN!' if current_user.role != "ADMIN"
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<%= form_with model:@quiz, local: true do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </p>
  <% if !@quiz.new_record? %>
    <%= f.select :id, [@quiz.id], {}, {class:'invisible'} %>
  <% end %>
  <p>
    <%= f.label  :difficulty %>
    <%= f.select :difficulty, ['easy', 'medium','hard'], {}, {class:'form-select'} %>
  </p>
  <%= f.submit "Submit", class:'btn btn-primary col-2' %>
<% end %>

app/views/quizzes/edit.html.erb
<h1> Edit Quiz </h1>
<div class='d-flex align-items-center justify-content-center'>
  <div class='col-md-6'>
    <%= render 'form' %>
    <%= link_to "Back", show_quiz_path(id: @quiz.id), class:'btn btn-secondary col-2 mt-3' %>
  </div>
</div>

app/views/quizzes/new.html.erb
<h1> New Quiz </h1>
<div class='d-flex align-items-center justify-content-center'>
  <div class='col-6'>
    <%= render 'form' %>
  </div>
</div>

app/views/quizzes/show.html.erb
<div class="card text-center" style='background-color:black; border-color: rgb(83, 83, 83); border-width: 5px;'>
  <div class="card-header" style='background-color: rgb(83, 83, 83)'>
    <h4> <%= @quiz.name %> </h4>
  </div>
  <div class="card-body">
    <h5 class="card-title">Mode: <%= @quiz.difficulty %> </h5>
    <div class='row' style='margin-top:70px'>
      <div class='col-6'> 
        <%= link_to 'Edit', edit_quiz_path(id: @quiz.id), class:'btn btn-warning col-6' %>
      </div>
      <div class='col-6'>
        <%= link_to 'Delete', destroy_quiz_path(id: @quiz.id), class:'btn col-6', data:{turbo_method: :delete, turbo_confirm: 'Delete Quiz?'}, style:'background-color:red; color:white' %>
      </div>
  </div>
  <div class="card-footer text-muted mt-4" style='background-color: rgb(83, 83, 83);'>
    <%= link_to "PLAY", '#', class:'btn col-4', style:'background-color: #09ee23; color: darkblue' %>
  </div>
</div>